services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: orba
      POSTGRES_PASSWORD: orba_password
      POSTGRES_DB: orba
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://orba:orba_password@postgres:5432/orba
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=change-this-to-a-random-secret
    depends_on:
      - postgres

volumes:
  postgres_data:
